task_02 ready for review
brstu/MMIPU-2020 pull request #148
Opened 2020-12-14 20:21 UTC by SomeoneWithBFG

2020-12-14 20:21 UTC, SomeoneWithBFG commented
Orayew Kerwen has problem with auth in git console, so we decided to open his PR using my account

2020-12-15 05:40 UTC, idzm requested changes

2020-12-15 05:40 UTC, idzm commented on trunk/as005321/task_02/doc/readme.md
> +#### Student: Zaichuk Daniil
Who is the author?

2020-12-25 18:32 UTC, idzm approved these changes

2020-12-25 18:32 UTC, merged