[Task_03] Work with AXC F 2152 controller
brstu/MMIPU-2020 pull request #169
Opened 2020-12-20 19:03 UTC by as005403

2020-12-20 19:05 UTC, as005411 requested changes
Unnecessary binary files. Please delete every thing extra.

2020-12-20 19:16 UTC, as005411 approved these changes
Its great now.

2020-12-20 19:26 UTC, as005403 commented
> Its great now.

>

2020-12-25 18:22 UTC, idzm approved these changes

2020-12-25 18:22 UTC, merged