dev_branchuk
brstu/MMIPU-2020 pull request #18
Opened 2020-09-29 22:35 UTC by dbranchuk

2020-10-01 11:19 UTC, idzm requested changes
Add VC project files.

2020-10-02 05:38 UTC, idzm approved these changes

2020-10-02 05:38 UTC, merged

2020-10-02 05:46 UTC, idzm commented on .idea/MMIPU-2020.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Удалить данный каталог (.idea) из корневой директории.

2020-10-02 05:46 UTC, idzm commented on trunk/dbranchuk/task_01/doc/readme.md
> +**Student: Branchuk Dima AS-53**
Файлы должны находится в каталоге `trunk/as00xxyy`.

2020-10-02 14:09 UTC, dbranchuk commented on trunk/dbranchuk/task_01/doc/readme.md
> +**Student: Branchuk Dima AS-53**
Немного накосячил,вышлю новый pull request со всеми изменениями,извиняюсь за неудобства.

2020-10-02 14:14 UTC, dbranchuk commented on .idea/MMIPU-2020.iml
> +<?xml version="1.0" encoding="UTF-8"?>
deleted