Task01 created cpp file and readme.md
brstu/MMIPU-2020 pull request #21
Opened 2020-10-01 21:29 UTC by Ann1ks

2020-10-02 17:04 UTC, as005411 commented
Folder should be named as0053xx (xx is your number in group) not your username.

2020-10-03 17:09 UTC, as005411 requested changes
Mistake in nonlinear equation.
Everything else is nice

2020-10-03 17:09 UTC, as005411 commented on trunk/as005302/doc/readme.md
> +        y = a * y - b * y * y + c * u + d * sin(u);
Mistake in b*y*y. Should be y(t-1) instead of y(t).

2020-10-08 08:59 UTC, as005411 requested changes
.vs folder is redundant.
Delete this folder and you're good to go

2020-10-09 11:08 UTC, as005411 approved these changes
Good job. Well done

2020-10-11 22:26 UTC, as005411 approved these changes
This should be an example for all of your group. Nice work

2020-10-12 07:20 UTC, Ann1ks commented
Thanks :)

On Mon, Oct 12, 2020, 01:26 Виталий Рахлей <notifications@github.com> wrote:

> *@as005411* approved this pull request.
>
> This should be an example for all of your group. Nice work
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/brstu/MMIPU-2020/pull/21#pullrequestreview-506222682>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJV7ENET2H7TON23JQFXEYDSKIWKRANCNFSM4SA6T2DQ>
> .
>

2020-10-15 07:24 UTC, idzm approved these changes

2020-10-15 07:25 UTC, merged