task01 added source code and documentation
brstu/MMIPU-2020 pull request #26
Opened 2020-10-03 11:05 UTC by gafffgona

2020-10-03 16:15 UTC, as005411 commented
Mistake in non-linear equation.

2020-10-03 16:26 UTC, as005411 requested changes
Mistake in non-linear equation.
Add task tag to the name.

Project itself is nice.

2020-10-03 16:26 UTC, as005411 commented on trunk/as005308/task_01/doc/readme.md
> +		y = a * y - b * pow(y,2) + c * u + d * sin(u);
y in pow(y,2) should be y(t-1) not y(t)

2020-11-04 07:16 UTC, idzm approved these changes

2020-11-04 07:16 UTC, merged